import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";
import ScrollToTopButton from "@/components/layout/ScrollToTopButton";
import localFont from 'next/font/local'
 
const siena = localFont({
  src: '../public/fonts/Avenir Light/Avenir Light.ttf',
})
 


export const metadata: Metadata = {
  title: "Clé Blanche Souissi - Élégance et Exclusivité à Rabat",
  description: "Generated by create next app",
};

// const unbounded = Montserrat({
//   subsets: ["vietnamese"],
//   weight: ["400", "500", "600", "700", "300", "800"],
// });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${siena.className} antialiased`}>
        <NavBar />
        {children}
        <ScrollToTopButton />
        <Footer />
      </body>
    </html>
  );
}
